name: build

on:
  push:
    branches: ["**"]
    tags: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-15'
        with:
          xcode-version: latest-stable

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Display PlatformIO Information
        run: |
          pio system info
          g++ --version
          gcc --version

      - name: build
        run: pio run

      - name: test
        if: matrix.os != 'windows-latest'
        run: pio test -e native -v

      - name: test (windows)
        if: matrix.os == 'windows-latest'
        run: pio test -e native-windows -v

      - name: static analysis
        run: pio check --skip-packages --fail-on-defect high

  publish-engineering-build:
    needs: build-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/publish-firmware.yml
    with:
      include_git_hash_in_firmware_version: true
      filename_suffix_type: git_short_hash

  publish-tagged-build:
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/publish-firmware.yml
    with:
      include_git_hash_in_firmware_version: false
      filename_suffix_type: git_tag
